### ISSUE TITLE
Apollo Logger throws error when we use this with apollo gateway

### ISSUE THREAD

**Issue by riginoommen** [shellscape/apollo-log#4] opened 2020-04-16 15:13 UTC
- Webpack Version: 4.41.5
- Operating System (or Browser): Google Chrome v80.0.3987.163 on MacOS 10.15.4
- Node Version: v10.15.3
- webpack-plugin-serve Version: 0.12.1

### How Do We Reproduce?

When we use this extension with the apolloserver  asoociated with apollo gateway  it throws error on the playground

Code segment is below

``` js
import express from 'express';
import { ApolloServer } from 'apollo-server-express';
import fs from 'fs';
import https from 'https';
import http from 'http';
import { ApolloGateway } from '@apollo/gateway';
import cookieParser from 'cookie-parser';
import { serviceList } from './src/helpers';
const { ApolloLogExtension } = require( 'apollo-log' );

/* Setting port for the server */
const port = process.env.PORT || 4000;
const app = express();

/* Mount cookie parker */
app.use( cookieParser() );

const extensions = [ () => new ApolloLogExtension( {
  level: 'info',
  timestamp: true,
} ) ];

/* Defining the Apollo Gateway */
const apiGateway = new ApolloGateway( {
  serviceList: serviceList
} );

/*  Creating the server based on the environment */
const server = process.env.NODE_ENV !== 'test'
  ? https.createServer(
    {
      key: fs.readFileSync( ( process.env.SSL_KEY ) ? `${ process.env.SSL_KEY }` : '' ),
      cert: fs.readFileSync( ( process.env.SSL_CERT ) ? `${ process.env.SSL_CERT }` : '' )
    },
    app
  )
  : http.createServer( app );
/* Binding the gateway with the apollo server and extracting the schema */
( async () => {
  const { schema, executor } = await apiGateway.load();
  /* Defining the Apollo Server */
  const apollo = new ApolloServer( {
    schema: schema,
    executor: executor,
    playground: process.env.NODE_ENV !== 'production',
    subscriptions: false,
    formatError: error => ( {
      message: error.message,
      locations: error.locations,
      stack: error.stack ? error.stack.split( '\n' ) : [],
      path: error.path,
    } ),
    extensions
  },
  );

  /* Applying apollo middleware to express server */
  apollo.applyMiddleware( { app } );
  server.listen( { port: port }, () => {
    console.log( `Gateway Running on port ${ port }` );
  } );
} )();

export default server;

```

Error that we get on playground is 

```js
{
  "error": {
    "errors": [
      {
        "message": "this[MAP][key].join is not a function",
        "stack": []
      }
    ]
  }
}
```

**Comment by shellscape** [comment] 2020-04-16 16:46
You're going to have to find the cause on your end, or give me an extremely minimal reproduction in a repo link. Otherwise I won't be able to help you triage this.

**Comment by shellscape** [comment] 2020-05-20 14:43
Closing as abandoned.

**Closed as completed by shellscape** 2020-05-20 14:43 UTC
